### PR TITLE
FDK context improvements

### PR DESCRIPTION
**Pull request by denismakogon**
New FDK context attributes:
 - request URL
 - method

Closes: #19

### CODE REVIEW

**Comment by zootalures** [comment]
LGTM: 
```
func myHandler(ctx context.Context, in io.Reader, out io.Writer) {
        p := &Person{Name: "World"}
        fnctx := fdk.Context(ctx)
        log.Printf("Got context %s %s",fnctx.Method, fnctx.RequestURL)
        json.NewDecoder(in).Decode(p)
        msg := struct {
                Msg string `json:"message"`
        }{
                Msg: fmt.Sprintf("Hello %s", p.Name),
        }
        json.NewEncoder(out).Encode(&msg)
}

```

```
$ fn call fooap gofn 
% fn logs get fooapp last 
2018/04/17 17:30:51 Got context GET http://localhost:8080/r/fooap/gofn
```

**Comment by rdallman** [comment]
it would be nice to nest these in something like `HTTP` struct instead of the top level, since not all functions invoked will have a request url or method soon enough. seems like something we can manage now even though it seems likely a lot of this breaks but i don't know for sure.

**Comment by rdallman** [comment]
i guess headers logically would move too, in that case. ok... we can punt.

**Comment by denismakogon** [comment]
I do understand that upcoming changes would break things apart. However, at this moment, there's a need to get the invocation URL. In my case, there's a function that polls Fn for calls and builds stats for 3rd-party service, so, i have to put Fn API URL to the config, which is ok, but feels weird. Imagine that Fn is a class and each function is a class method, so i want to do something like this `this.calls`. That's why i need Fn API URL or request URL that is fine as well.

**Comment by denismakogon** [comment]
call ID - maybe, who knows, what's the real application except logging of the call ID?
deadline - no, FDK already starts the context with a deadline, so it's not useful for developers.

**Comment by rdallman** [comment]
call id is available through http, not really a debate about usefulness it's a parity issue at this point. that's right about deadline.

**Pull request merged**
